name: Notify Dependency Update

on:
  push:
    branches:
      - master

jobs:
  notify-dependency-update:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Dependency Change
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.MAIN_REPO_PAT }}" \
            https://api.github.com/repos/PraveenGongada/nodejs-graphql/dispatches \
            -d '{"event_type": "dependency-updated", "client_payload": {"branch": "main", "library-name": "react-native-maps"}}'
